version: '3'
services:
    app:
        image: php:8.0-fpm
        container_name: laravel-app
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        environment:
            - "APP_ENV=local"
            - "APP_DEBUG=true"
            - "APP_KEY=base64:BVIstTTzx20XxuQ0fMxhZ2Z0yfR2kUsMlxL/3DKMa6E="
            - "DB_CONNECTION=mysql"
            - "DB_HOST=db"
            - "DB_PORT=3306"
            - "DB_DATABASE=my_database"
            - "DB_USERNAME=root"
            - "DB_PASSWORD=my_password"
        depends_on:
                - db
        networks:
            - app-network

    webserver:
        image: nginx:alpine
        container_name: laravel-webserver
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - app-network

    db:
        image: mysql:5.7
        container_name: laravel-mysql
        environment:
            - "MYSQL_DATABASE=my_database"
            - "MYSQL_PASSWORD=my_password"
            - "MYSQL_ROOT_PASSWORD=my_password"
        ports:
            - "3306:3306"
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laravel-phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: my_password
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
